services:
  application-dev:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: application-dev
    command: ["node", "app.js"]
    volumes:
      - ./application:/usr/src/app
    ports:
      - "3001:3000"
    networks:
      - testnet

networks:
  testnet:
    external: true
