services:
  application-prod:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: application-prod
    command: ["node", "app.js"]
    ports:
      - "3000:3000"
    networks:
      - testnet

networks:
  testnet:
    external: true
