version: "3.8"

services:
  application:
    build: ./application
    environment:
      - PORT=3000
      - BG_COLOR=green
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - application
    volumes:
      - /home/azureuser/dev_tls:/dev_tls