version: "3.8"
services:
  application:
    build: ./application
    container_name: application-prod
    environment:
      - PORT=3000
      - BG_COLOR=purple
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot;
      sleep 12h & wait $${!}; done"
