services:
  application-dev:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: application-dev
    command: ["node", "app.js"]
    environment:
      - BG_COLOR=green
    networks:
      - testnet
    
networks:
  testnet:
    external: true