version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /home/azureuser/tls:tls
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - application-dev
      - application-prod
    networks:
      - testnet

networks:
  testnet:
    external: true
