name: Deploy to Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Checkout Ansible repository
        uses: actions/checkout@v4
        with:
          repository: Andriy29k/Ansible_to_test_task.git
          ref: main
          path: ansible
          token: ${{ secrets.TOKEN }}
        
      - name: Debug Ansible repository contents
        run: |
          ls -la ansible/
          ls -la ansible/roles/
          echo "Checking for playbook.yaml"
          if [ -f ansible/playbook.yaml ]; then echo "playbook.yaml found"; else echo "playbook.yaml NOT found"; fi
          if [ -f ansible/playbook.yml ]; then echo "playbook.yml found"; else echo "playbook.yml NOT found"; fi

      - name: Create temporary TLS certificate files
        run: |
          mkdir -p ansible/roles/copy_tls/files/tls
          echo "${{ secrets.TLS_CERT_PEM }}" > ansible/roles/copy_tls/files/tls/cert.pem
          echo "${{ secrets.TLS_KEY_PEM }}" > ansible/roles/copy_tls/files/tls/key.pem
          chmod 600 ansible/roles/copy_tls/files/tls/*

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible on runner
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create SSH config
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/test.pem
          echo "${{ secrets.SSH_CONFIG }}" > ansible/ssh_config.conf

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H {{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


      - name: Create Inventory file
        run: |
          echo "${{ secrets.INVENTORY }}" > ansible/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml