name: Deploy to Dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Checkout Ansible repository
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Andriy29k/Ansible_to_test_task.git
          ref: main
          path: ansible
          token: ${{ secrets.TOKEN }}

      - name: Create temporary TLS certificate files
        run: |
          mkdir -p ansible/roles/copy_tls/files/tls
          echo "${{ secrets.TLS_CERT_PEM }}" > ansible/roles/copy_tls/files/tls/cert.pem
          echo "${{ secrets.TLS_KEY_PEM }}" > ansible/roles/copy_tls/files/tls/key.pem
          chmod 600 ansible/roles/copy_tls/files/tls/*

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible on runner
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Copy Ansible files to server
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@134.33.64.215 "mkdir -p ~/ansible"
          scp -r ansible/* azureuser@134.33.64.215:~/ansible

      - name: Run Ansible Playbook on server
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@134.33.64.215 "cd ~/ansible && ansible-playbook playbook.yml -i inventory.yml"
